// Chambered.Api/client/src/views/Login.tsx
import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useStore } from "../StoreContext";
import {
  postUsersRegister,
  useGetAccountConfiguredProviders,
  getGetAccountPrepareChallengeUrl,
  useGetSettingsLoginSettings,
} from "../api/endpoints";
import "./Login.css";
import "../components/VersionControl.tsx";
import { VersionControl } from "../components/VersionControl.tsx";

interface PasswordStrengthInfo {
  score: number;
  label: string;
  className: string;
}

export default function Login() {
  const store = useStore();
  const navigate = useNavigate();

  const [username, setUsername] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const [email, setEmail] = useState<string>("");
  const [confirmPassword, setConfirmPassword] = useState<string>("");
  const [isSubmitting, setIsSubmitting] = useState<boolean>(false);
  const [errorMessage, setErrorMessage] = useState<string>("");

  const [mode, setMode] = useState<"setup" | "login" | "register">(() => {
    if (store.isInitialized === false) return "setup";
    return "login";
  });

  // Synchronize dynamic setup mode if store loads initialized state asynchronously
  useEffect(() => {
    if (store.isInitialized === false) {
      setMode("setup");
    } else if (store.isInitialized === true && mode === "setup") {
      setMode("login");
    }
  }, [store.isInitialized, mode]);

  // Simple real-time password strength validation score: 0 to 4
  const getPasswordStrength = (pwd: string): PasswordStrengthInfo => {
    if (!pwd) return { score: 0, label: "", className: "" };
    let score = 1;
    if (pwd.length >= 8) score++;
    if (/[A-Z]/.test(pwd) && /[a-z]/.test(pwd)) score++;
    if (/[0-9]/.test(pwd)) score++;
    if (/[^A-Za-z0-9]/.test(pwd)) score++;

    const finalScore = Math.min(score, 4);
    let label = "Weak";
    let className = "weak";
    if (finalScore === 2) {
      label = "Fair";
      className = "fair";
    } else if (finalScore === 3) {
      label = "Good";
      className = "good";
    } else if (finalScore === 4) {
      label = "Strong";
      className = "strong";
    }
    return { score: finalScore, label, className };
  };

  const pwdStrength = getPasswordStrength(password);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMessage("");
    setIsSubmitting(true);

    try {
      if (mode === "setup") {
        const success = await store.firstRegister(username, password, email);
        if (success) {
          navigate("/");
        }
      } else if (mode === "login") {
        const success = await store.login(username, password);
        if (success) {
          navigate("/");
        }
      } else if (mode === "register") {
        if (password !== confirmPassword) {
          throw new Error("Passwords do not match.");
        }
        if (pwdStrength.score < 2) {
          throw new Error("Please choose a stronger password.");
        }

        try {
          const res = await postUsersRegister({
            username,
            email,
            password,
            firstName: username,
            lastName: "",
          });

          if (res.status === 200 || res.status === 201) {
            const loginSuccess = await store.login(username, password);
            if (loginSuccess) navigate("/");
          } else {
            throw new Error(
              (res.data as any)?.detail ||
                "Registration is restricted by administrators.",
            );
          }
        } catch (err: any) {
          throw new Error(
            err.message ||
              "Self-registration is restricted. Please contact your administrator.",
          );
        }
      }
    } catch (err: any) {
      setErrorMessage(
        err.message || "Authentication or profile creation failed.",
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  const {
    data: loginResponse,
  } = useGetSettingsLoginSettings();

  const loginPolicy = loginResponse?.data;

  // Fetch configured providers from the backend (/api/v1/Account/providers)
  const { data: providersResponse } = useGetAccountConfiguredProviders();
  const oidcProviders = (providersResponse?.data as string[]) || [];

  const handleOidcLogin = (providerName: string) => {
    const redirectUri = `${window.location.origin}/`;

    // Dynamically build the versioned URL using Orval's generated builder function
    const challengeUrl = getGetAccountPrepareChallengeUrl({
      providerName,
      redirectUri,
    });

    window.location.href = challengeUrl;
  };

  return (
    <div className="login-page">
      <div className="login-card">
        {/* Sleek Dynamic Brand Header */}
        <div className="brand">
          <span className="brand-emoji">🛡️</span>
          {mode === "setup" ? (
            <>
              <h1 className="brand-name font-setup">CHAMBERED</h1>
              <p className="brand-subtitle">First-run setup · step 1 of 1</p>
            </>
          ) : mode === "register" ? (
            <>
              <h1 className="brand-name">CHAMBERED</h1>
              <p className="brand-subtitle">Create your new user account</p>
            </>
          ) : (
            <>
              <h1 className="brand-name">CHAMBERED</h1>
              <p className="brand-subtitle">
                Precision armory & ammunition server
              </p>
            </>
          )}
        </div>

        {/* Informative Banner for Setup Onboarding */}
        {mode === "setup" && (
          <div className="setup-banner">
            No profiles found. This first account becomes{" "}
            <strong>System Owner</strong> with full administrative rights.
          </div>
        )}

        {errorMessage && (
          <div className="error-banner" style={{ marginBottom: "20px" }}>
            {errorMessage}
          </div>
        )}

        {!loginPolicy?.disableLocalUsers ? (
          <form onSubmit={handleSubmit} className="login-form">
            <div className="form-group">
              <label htmlFor="username">Username</label>
              <input
                type="text"
                id="username"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                placeholder={
                  mode === "setup" ? "e.g. administrator" : "administrator"
                }
                required
                disabled={isSubmitting}
              />
            </div>

            {/* Email field (only in Setup and Register modes) */}
            {(mode === "setup" || mode === "register") && (
              <div className="form-group">
                <label htmlFor="email">
                  Email Address {mode === "setup" && "· optional"}
                </label>
                <input
                  type="email"
                  id="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="admin@domain.local"
                  required={mode === "register"}
                  disabled={isSubmitting}
                />
              </div>
            )}

            <div className="form-group">
              <div className="form-group-header">
                <label htmlFor="password">Password</label>
                {mode === "login" && (
                  <a
                    href="#forgot"
                    tabIndex={-1}
                    onClick={(e) => {
                      e.preventDefault();
                      alert(
                        "Please contact your administrator to reset your credentials.",
                      );
                    }}
                    className="forgot-password-link"
                  >
                    Forgot?
                  </a>
                )}
              </div>
              <input
                type="password"
                id="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="••••••••"
                required
                disabled={isSubmitting}
              />
            </div>

            {/* Reactive Segmented Strength Indicator for Setup and Register */}
            {(mode === "setup" || mode === "register") && (
              <div className="password-strength">
                <div className="password-strength-bar">
                  <div
                    className={`strength-segment ${pwdStrength.score >= 1 ? `active-${pwdStrength.className}` : ""}`}
                  />
                  <div
                    className={`strength-segment ${pwdStrength.score >= 2 ? `active-${pwdStrength.className}` : ""}`}
                  />
                  <div
                    className={`strength-segment ${pwdStrength.score >= 3 ? `active-${pwdStrength.className}` : ""}`}
                  />
                  <div
                    className={`strength-segment ${pwdStrength.score >= 4 ? `active-${pwdStrength.className}` : ""}`}
                  />
                </div>
                {password && pwdStrength.label && (
                  <div className={`strength-text ${pwdStrength.className}`}>
                    {pwdStrength.label}
                  </div>
                )}
              </div>
            )}

            {/* Password confirmation for Register mode */}
            {mode === "register" && (
              <div className="form-group">
                <label htmlFor="confirmPassword">Confirm Password</label>
                <input
                  type="password"
                  id="confirmPassword"
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  placeholder="••••••••"
                  required
                  disabled={isSubmitting}
                />
              </div>
            )}

            <button
              type="submit"
              className="btn btn-primary login-btn"
              disabled={isSubmitting}
            >
              {isSubmitting ? (
                <span className="mini-spinner"></span>
              ) : mode === "setup" ? (
                "Initialize server & sign in"
              ) : mode === "register" ? (
                "Create Account & Sign In"
              ) : (
                "Access Armory"
              )}
            </button>
          </form>
        ) : (
          <div
            className="setup-banner"
            style={{
              margin: "0 0 20px 0",
              border: "1px dashed rgba(255, 255, 255, 0.1)",
            }}
          >
            Local authentication is disabled. Please authenticate using OIDC
            Single Sign-On below.
          </div>
        )}

        {/* Dynamic SSO Buttons Section */}
        {mode === "login" && oidcProviders.length > 0 && (
          <>
            <div className="sso-divider">
              <span>or connect via</span>
            </div>

            <div
              className="sso-actions"
              style={{ display: "flex", flexDirection: "column", gap: "10px" }}
            >
              {oidcProviders.map((providerName) => (
                <button
                  key={providerName}
                  onClick={() => handleOidcLogin(providerName)}
                  className="btn btn-secondary sso-btn"
                  disabled={isSubmitting}
                >
                  <span>{providerName}</span>
                </button>
              ))}
            </div>
          </>
        )}

        {/* Seamless Navigation Mode Toggles */}
        {store.isInitialized && (
          <div className="auth-toggle-container">
            {mode === "login" ? (
              !loginPolicy?.disableNewUserRegistration && (
                <>
                  New user?
                  <button
                    type="button"
                    onClick={() => {
                      setErrorMessage("");
                      setMode("register");
                    }}
                    className="auth-toggle-link"
                  >
                    Create an account
                  </button>
                </>
              )
            ) : (
              <>
                Already have an account?
                <button
                  type="button"
                  onClick={() => {
                    setErrorMessage("");
                    setMode("login");
                  }}
                  className="auth-toggle-link"
                >
                  Sign in
                </button>
              </>
            )}
          </div>
        )}

        {/* System Version Footer */}
        <div className="login-footer">
          <p>
            {mode === "setup" ? (
              "First-run initialization protocol active"
            ) : (
              <>
                <VersionControl />
              </>
            )}
          </p>
        </div>
      </div>
    </div>
  );
}

// Chambered.Api/client/src/views/Login.vue
<template>
  <div class="login-page">
    <div class="login-card">
      <div class="brand">
        <span class="brand-emoji">🔥</span>
        <h1 class="brand-name" :class="{ 'font-setup': !store.isInitialized && store.isInitialized !== null }">
          {{ store.isInitialized ? 'CHAMBERED' : 'CHAMBERED SETUP' }}
        </h1>
        <p class="brand-subtitle">
          {{ store.isInitialized ? 'Precision Armory & Ammunition Server' : 'Register Primary Owner Account' }}
        </p>
      </div>

      <div class="setup-banner" v-if="!store.isInitialized && store.isInitialized !== null">
        Welcome! No user profiles found. The first account created will be granted <strong>System Owner (Administrator)</strong> credentials.
      </div>

      <form @submit.prevent="handleSubmit" class="login-form">
        <div class="error-banner" v-if="errorMessage">
          {{ errorMessage }}
        </div>

        <div class="form-group">
          <label for="username">Username</label>
          <input 
            type="text" 
            id="username" 
            v-model="username" 
            placeholder="e.g. administrator" 
            required 
            :disabled="isSubmitting"
          />
        </div>

        <!-- Optional email profile field during onboarding -->
        <div class="form-group" v-if="!store.isInitialized && store.isInitialized !== null">
          <label for="email">Email Address</label>
          <input 
            type="email" 
            id="email" 
            v-model="email" 
            placeholder="admin@domain.local" 
            :disabled="isSubmitting"
          />
        </div>

        <div class="form-group">
          <label for="password">Password</label>
          <input 
            type="password" 
            id="password" 
            v-model="password" 
            placeholder="••••••••" 
            required 
            :disabled="isSubmitting"
          />
        </div>

        <button type="submit" class="btn btn-primary login-btn" :disabled="isSubmitting">
          <span v-if="isSubmitting" class="mini-spinner"></span>
          <span v-else-if="store.isInitialized">Access Armory</span>
          <span v-else>Initialize Server & Sign In</span>
        </button>
      </form>

      <!-- SSO connection selectors, hidden on clean setups -->
      <template v-if="store.isInitialized">
        <div class="sso-divider">
          <span>or connect via</span>
        </div>

        <div class="sso-actions">
          <button @click="handleOidcLogin" class="btn btn-secondary sso-btn">
            <span class="sso-icon"></span>
            <span>Sign In with OIDC Single Sign-On</span>
          </button>
        </div>
      </template>

      <div class="login-footer">
        <p v-if="store.isInitialized">Protected by Mixed Casing Authentication</p>
        <p v-else>First-run initialization protocol active</p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { store } from '../store'

const router = useRouter()
const username = ref('')
const password = ref('')
const email = ref('')
const isSubmitting = ref(false)
const errorMessage = ref('')

const handleSubmit = async () => {
  errorMessage.value = ''
  isSubmitting.value = true
  try {
    if (store.isInitialized === false) {
      const success = await store.firstRegister(username.value, password.value, email.value)
      if (success) {
        router.push('/')
      }
    } else {
      const success = await store.login(username.value, password.value)
      if (success) {
        router.push('/')
      }
    }
  } catch (err) {
    errorMessage.value = err.message || 'Verification or profile creation failed.'
  } finally {
    isSubmitting.value = false
  }
}

const handleOidcLogin = () => {
  window.location.href = '/api/auth/oidc/login'
}
</script>

<style scoped>
.login-page {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  width: 100vw;
  background-color: var(--bg-main);
  background-image: 
    radial-gradient(circle at 10% 20%, rgba(204, 164, 59, 0.04) 0%, transparent 45%),
    radial-gradient(circle at 90% 80%, rgba(210, 124, 45, 0.03) 0%, transparent 45%);
  position: fixed;
  top: 0;
  left: 0;
  z-index: 1000;
  overflow: hidden;
}

.login-card {
  width: 100%;
  max-width: 440px;
  background-color: var(--bg-panel);
  border: 1px solid var(--border-light);
  border-radius: var(--radius-lg);
  padding: 40px;
  box-shadow: 0 10px 40px rgba(0, 0, 0, 0.6), 0 0 30px rgba(204, 164, 59, 0.05);
  display: flex;
  flex-direction: column;
}

.brand {
  text-align: center;
  margin-bottom: 28px;
}

.brand-emoji {
  font-size: 40px;
  display: inline-block;
  margin-bottom: 12px;
  filter: drop-shadow(0 0 10px rgba(204, 164, 59, 0.4));
}

.brand-name {
  font-family: var(--font-heading);
  font-size: 26px;
  font-weight: 800;
  color: var(--color-primary);
  letter-spacing: 0.12em;
}

.font-setup {
  font-size: 21px !important;
  letter-spacing: 0.08em;
}

.brand-subtitle {
  font-size: 13px;
  color: var(--text-secondary);
  margin-top: 6px;
}

.setup-banner {
  background: rgba(204, 164, 59, 0.06);
  color: var(--text-primary);
  border: 1px solid rgba(204, 164, 59, 0.15);
  padding: 14px;
  border-radius: var(--radius-sm);
  font-size: 13px;
  line-height: 1.5;
  margin-bottom: 24px;
  text-align: center;
}

.login-form {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.error-banner {
  background: rgba(239, 68, 68, 0.1);
  color: var(--color-danger);
  border: 1px solid rgba(239, 68, 68, 0.2);
  padding: 12px;
  border-radius: var(--radius-sm);
  font-size: 13px;
  line-height: 1.4;
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.form-group label {
  font-family: var(--font-heading);
  font-size: 12px;
  font-weight: 600;
  color: var(--text-secondary);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.login-btn {
  width: 100%;
  padding: 12px;
  font-size: 15px;
  font-weight: 600;
  margin-top: 8px;
}

.mini-spinner {
  width: 18px;
  height: 18px;
  border: 2px solid rgba(0, 0, 0, 0.1);
  border-top-color: var(--bg-main);
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
}

.sso-divider {
  display: flex;
  align-items: center;
  text-align: center;
  margin: 24px 0;
  color: var(--text-muted);
  font-size: 12px;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.sso-divider::before, .sso-divider::after {
  content: '';
  flex: 1;
  border-bottom: 1px solid var(--border-solid);
}

.sso-divider span {
  padding: 0 10px;
}

.sso-btn {
  width: 100%;
  padding: 12px;
  font-size: 14px;
}

.sso-icon {
  font-size: 16px;
}

.login-footer {
  text-align: center;
  margin-top: 32px;
  font-size: 11px;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.08em;
}
</style>
